### ISSUE TITLE
fontawesome version used?

### ISSUE THREAD

**Issue by kabaluyot** [emiliogrv/nativescript-vue-fonticon#5]
Is this implemented with fontawesome 5+ ?

**Comment by eaglejs** [comment]
I assume this is version 4.7.0 based on the file structure, you can find it here.

https://fontawesome.com/v4.7.0/get-started/

I'll be honest though, I have yet to even get this solution working. I'm working on it as well. :)

**Comment by kabaluyot** [comment]
Oh. The nativescript-fonticon is working?

**Comment by eaglejs** [comment]
I couldn't get it to work in the current version of NativeScript Vue. This link here is the only thing I can find that works. *NOTE* this is using font awesome 5

https://www.gitmemory.com/issue/NathanWalker/nativescript-fonticon/14/493559957

incase the link doesn't work...

install nativescript-fonticon [Official guide](https://github.com/NathanWalker/nativescript-fonticon)

`npm install nativescript-fonticon --save`
Then I visited the page [Hosting Font Awesome Yourself](https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself) and [downloaded the zip](https://use.fontawesome.com/releases/v5.8.2/fontawesome-free-5.8.2-web.zip).

Extracted, I copied webfonts/fa-solid-900.ttf into my project's folder app/fonts. Then I renamed as `Font Awesome Free 5 Solid.ttf`, because on IOS font file name must match font full name. And this is is how Apple's Font Book identifies my font, it's the full name of the font.

I then copied css/fontawesome.css into my project as app/fontawesome.css.

I modified app/components/app.vue as follows

```
<template>
    <Page>
        <GridLayout columns="*" rows="*">
            <Label class="message fa" text.decode="&#xf252;" col="0" row="0"/>
        </GridLayout>
    </Page>
</template>
```

I edit my app.scss file as follows

```
@import 'fontawesome.css';

.fa,
.fas {
  font-family: "Font Awesome Free 5 Solid";
}
```
`tns debug ios` or `tns debug android`

**Comment by eaglejs** [comment]
I'm not a big fan of this solution because of the text.decode and using unicode... but I don't know how else to fix it. I did notice the other ways work, however, only when I close the app and reopen it. It's very weird.

**Comment by kabaluyot** [comment]
Yeah. Thanks for the heads up. Maybe a workaround for the text.decoode and unicode is to map it.

**Comment by kabaluyot** [comment]
Anyways the version is answered. Closing this ticket.
